apiVersion: apps/v1
kind: Deployment
metadata:
  name: spotify-clone
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spotify-clone
  template:
    metadata:
      labels:
        app: spotify-clone
    spec:
      containers:
        - name: spotify-clone
          image: spotify-clone
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: production
          resources:
            limits:
              memory: "512Mi"
              cpu: "0.5"
            requests:
              memory: "256Mi"
              cpu: "0.25"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/info
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10